### ISSUE TITLE
Chrome under Ubuntu 19.10 does

### ISSUE THREAD

**Issue by baqwas** [arduino/ArduinoAI#1]
Hello,

At the suggestion of @sandeepmistry I am transferring this issue to this site. The Nano 33 BLE Sense board is working with basic sensor test exercises (via BLE) with the **Ubuntu 19.10** desktop client Arduino IDE. Unfortunately, the demo posted earlier this week does not work with a fresh install of **Chrome** as described below:

My steps are:

- Rushed to practice the suggestion posted at https://twitter.com/arduino/status/1201957810084483074

- Compiled sketch (_without any change_) under desktop IDE after installing one missing library

- Uploaded sketch to Nano33 BLE board

- Launched **Google Chrome** (Version 78.0.3904.108 (Official Build) (64-bit)) under **Ubuntu 19.10** (desktop) and received error message:

```
arduino.github.io says
Error: This browser doesn't support Web Bluetooth. Try using Chrome.
OK.
```

I receive the same error when building using the Arduino Cloud IDE.

Please provide some suggestion on correcting my mistake with any recommended workaround. I am a beginner in these matters. I can post or redirect this inquiry elsewhere upon suggestion.

Kind regards.

**Comment by ajosephau** [comment]
Hope you don't mind the suggestion... but is the Chrome flag for Web Bluetooth enabled?

The setting is available at: chrome://flags/#enable-experimental-web-platform-features , and information about this feature is available at: https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web .

**Comment by baqwas** [comment]
@ajosephau Thx for the suggestion. I duly visited the link you provided. WOW! It was like entering another dimension (or cavern) with so many things to enable/disable. I didn't find any reference to 

> "Chrome flag for Web Bluetooth"

during several up/down cursory scrolling on the page. I will continue to look more finely into the settings because you have pointed out a potential setting in my default environment. Many thanks for your suggestion; I now have some work to do at my end to ensure that I set Chrome properly to receive the BLE messages.

I would like to keep the issue open for at least one more iteration while I work on setting Chrome correctly at my end. I can then hopefully report on the steps that I performed to set the handshake correctly.

Kind regards.

**Comment by baqwas** [comment]
@ajosephau 
OK, _operator error_ on my part, sorry! (Not a Chrome person is my poor defence)

Thanks to your guidance found three settings that I enabled:

- Experimental Web Platform features
- Web Authentication API BLE support
- Web Authentication caBLE support

Will worry about which specific one did the trick later. The dashboard is now receiving messages! Many thanks, again.

Kind regards.
