### ISSUE TITLE
NiclaSenseME.ino: Use of undeclared identifier 'NICLA_STANDALONE'

### ISSUE THREAD

**Issue by gmacario** [arduino/ArduinoAI#11]
I tried to compile sketch NiclaSenseME.ino from https://github.com/arduino/ArduinoAI/tree/main/NiclaSenseME-dashboard/NiclaSenseME using

* Arduino IDE 2.0.0-rc8 on Windows 10
* Arduino Mbed OS Nicla Boards Version 3.1.1
* Library ArduinoBLE by Arduino Version 1.3.1
* Library Arduino_BHY2 by Arduino Version 1.0.5

but I got the following error:

![image](https://user-images.githubusercontent.com/75182/189052585-e4e1677f-a283-4ecf-8db0-f8d97a8f23e4.png)

**Comment by gmacario** [comment]
I guess the problem is related to https://github.com/arduino/ArduinoAI/pull/10/commits/21445fe168d662a44e45df193ef4b325830daca4

According to https://github.com/arduino/ArduinoAI/pull/10

> Update BHY2 begin command for the latest version of the library

@marqdevx, @mbanzi which is the latest version of the BHY2 library which you referred to?

As reported I am using Version 1.0.5 which if I am not mistaken is the latest publicly available as of today:

![image](https://user-images.githubusercontent.com/75182/189053586-84e4a359-08eb-45ea-a788-dc0a6a98a06e.png)

**Comment by marqdevx** [comment]
@gmacario The `Arduino_BHY2` version should be v1.0.6
https://github.com/arduino-libraries/Arduino_BHY2/releases

**Comment by gmacario** [comment]
> @gmacario The `Arduino_BHY2` version should be v1.0.6 https://github.com/arduino-libraries/Arduino_BHY2/releases

Thanks @marqdevx for your clarification.

I installed Arduino IDE 2.0.0-rc9.4 on a new machine (Ubuntu 22.04) and there I could find version 1.0.6 of the Arduino_BHY2 library and successfully compile the sketch.

On the other hand, my original installation on Windows 10 (Arduino IDE 2.0.0-rc8) is still unable to update to a version later than v1.0.5 of the Arduino_BHY2 library...

**Comment by gmacario** [comment]
> On the other hand, my original installation on Windows 10 (Arduino IDE 2.0.0-rc8) is still unable to update to a version later than v1.0.5 of the Arduino_BHY2 library...

I removed my previous installation of Arduino IDE, deleted the Arduino libraries folder and performed a clean installation of

* Arduino IDE 2.0.0 for Windows (Win 10 and newer, 64 bits) now available at <https://www.arduino.cc/en/software>
* “Arduino Mbed OS Nicla Boards [v 3.3.0]” core
* library “Arduino_BHY2“ by Arduino Version 1.0.6
* library “ArduinoBLE” by Arduino Version 1.3.2

The sketch compiles without errors.
Closing issue.
